/* 
* @Purpose: Created for SU:621 requirement and  This is used to store current Pricing Request and Price.
* @Author: Rahul Ghaytadak
* @CreatedDate: 02/26/2021
* @Related Code: Batch_CreateCustomObjectRecord
* @Test Class: Create_Price_Summary_Test
* @LastModifiedDate: 02/26/2021
* @LastModifiedBy: Rahul Ghaytadak
*/
public class checkRecursive {
     Public static  ExperianLegalFilingSummariesFetcher.sendResponseData scoreResult = new ExperianLegalFilingSummariesFetcher.sendResponseData();
}